
class Policy:
    def __init__(self, content, cat, strength):
        self.content = content
        self.cat = cat
        self.strength = strength
    def get_head(self):
        return "_".join([self.strength, self.cat])
    
# POLICY_REPO = [
#     Policy("Our community is introducing the 'Vaccine Ambassador Program,' where caring volunteers like peers, nurses, and community health workers will attend local events to talk about vaccines. These ambassadors will offer basic information and answer simple questions in a friendly, casual way. You might meet them at a park meetup, a recovery center, or even a neighborhood fair. While they aren’t formally trained, they’ll have some resources to help explain how vaccines work. This is a low-pressure opportunity to chat and clear up any concerns. If you're curious but unsure, this program gives you a chance to hear a little more about vaccines in a relaxed setting, but it’s up to you whether you want to act.", "ambassador", "weak"),
#     Policy("Our community is launching the 'Vaccine Ambassador Program' to empower you with the information and support you need to protect yourself and your loved ones. Imagine a trusted, trained ambassador meeting you where you are—at a shelter, a community center, or even your local food bank—ready to listen to your concerns and provide clear, science-based answers about vaccines. These ambassadors are here to guide meaningful conversations, break down myths, and give you the confidence to make an informed choice. If you’ve ever worried about whether vaccines are right for you, this program ensures you don’t have to face those questions alone. By participating, you’ll join thousands of others in taking a step toward protecting your health and building a stronger, safer community for everyone.", "ambassador", "strong"),
#     Policy("The state government offers a small $10 cash card to adults who receive their first dose of vaccination. This limited-time incentive is available while supplies last.", "incentive", "weak"),
#     Policy("The state government guarantees a $50 cash card to all adults who either receive or transport someone to receive their first dose of vaccination. Additionally, targeted outreach will ensure residents in underserved areas are aware of and can access this enhanced incentive.", "incentive", "strong"),
#     Policy("Starting today, our state government encourages employees, students, and visitors to workplaces or schools to get vaccinated before entry. While getting vaccinated is strongly recommended to help protect yourself and those around you, this policy is largely voluntary, and enforcement will be left to the discretion of individual institutions. This means that schools and workplaces can decide how strictly to apply these recommendations. The goal is to create awareness and gently encourage compliance, trusting that most people will choose vaccination to safeguard their health and the well-being of their communities.", "mandate", "weak"),
#     Policy("Starting today, our state government requires vaccination for all employees, students, and visitors entering workplaces, schools, public venues, and transportation hubs. This mandate is a crucial step to protect everyone, ensuring safer spaces for you and your loved ones. Local health departments, with state oversight, will strictly enforce the policy, applying penalties for non-compliance in schools, government offices, and even public transportation. By choosing to vaccinate, you’re not just following a rule—you’re actively contributing to ending the threat of preventable illness in our communities. Together, we can create a healthier, more resilient future where everyone feels safe and protected.", "mandate", "strong")
# ]

# https://nhchc.org/research/vaccine-ambassador-project/#:~:text=The%20Centers%20for%20Disease%20Control,Vaccine%20Ambassador%20Project%20from%20November
# https://pmc.ncbi.nlm.nih.gov/articles/PMC9148933/#s0015
    
POLICY_REPO = [
    Policy("Our community is introducing the 'VaxUp Neighbors' program to raise basic awareness about vaccines. Volunteers will be available at community events, such as school gatherings or park meetups, to provide general information on vaccines. This effort, in collaboration with the County Health Department and PTA, encourages casual conversations to dispel myths and offer simple, reliable information about vaccinations. Participation is voluntary, and no formal training is required for volunteers, but they will have access to informational resources.", "ambassador", "weak"),
    # Policy("Our community is rolling out the 'VaxUp Neighbors' program to actively engage residents in conversations about vaccines. Volunteers will receive basic training to cover key topics like vaccine benefits and addressing common concerns. These volunteers will lead informal discussions in community spaces such as schools and parks. Supported by the County Health Department and PTA, they will also organize Q&A sessions to help residents make informed decisions about vaccinations. This effort focuses on increasing awareness and combating misinformation through direct community involvement.", "ambassador", "medium"),
    Policy("Our community is launching the 'VaxUp Neighbors' program, where fully trained volunteers will facilitate in-depth conversations about vaccines in various familiar settings like schools, parks, and community centers. In partnership with the County Health Department and PTA, these volunteers will complete a comprehensive training program, covering all aspects of vaccine safety, benefits, and myth-busting. They will lead interactive workshops, host Q&A sessions, and provide fact-based resources. This initiative aims to improve vaccine literacy and public health outcomes by equipping the community with the tools to make well-informed vaccination decisions.", "ambassador", "strong"),
    Policy("The state government offers a $10 cash card to adults who receive their first dose of FD. This limited-time incentive is available while supplies last.", "incentive", "weak"),
    Policy("The state government guarantees a $50 cash card to all adults who either receive or transport someone to receive their first dose of FD. Additionally, targeted outreach will ensure residents in underserved areas are aware of and can access this enhanced incentive.", "incentive", "strong"),
    # Policy("The state government guarantees a $25 cash card to adults who receive their first dose of FD or drive someone to receive theirs. This program aims to boost vaccination participation across the state.", "incentive", "medium"),
    Policy("Starting today, our state government strongly recommends that employees and students be vaccinated before entering workplaces or schools. Compliance is encouraged, but enforcement will be minimal, and institutions will have discretion in enforcing this policy.", "mandate", "weak"),
    # Policy("Starting today, our state government mandates vaccination for employees and students before entering workplaces or schools. Additionally, public venues such as gyms, restaurants, and event spaces will require proof of vaccination. Local health departments will conduct periodic checks to ensure compliance.", "mandate", "medium"),
    Policy("Starting today, our state government mandates that all employees, students, and individuals entering workplaces, schools, public venues, and transportation hubs be vaccinated. This policy will be strictly enforced by local health departments, with state oversight and penalties for non-compliance across all sectors, including public transportation and government buildings.", "mandate", "strong")
]